/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as CallRoomIdRouteImport } from './routes/call.$roomId'
import { Route as CamCodeRouteImport } from './routes/cam.$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoomIdRoute = CallRoomIdRouteImport.update({
  id: '/call/$roomId',
  path: '/call/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const CamCodeRoute = CamCodeRouteImport.update({
  id: '/cam/$code',
  path: '/cam/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/rtc': typeof ApiRtcRoute
  '/call/$roomId': typeof CallRoomIdRoute
  '/cam/$code': typeof CamCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/rtc': typeof ApiRtcRoute
  '/call/$roomId': typeof CallRoomIdRoute
  '/cam/$code': typeof CamCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/rtc': typeof ApiRtcRoute
  '/call/$roomId': typeof CallRoomIdRoute
  '/cam/$code': typeof CamCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/api/rtc' | '/call/$roomId' | '/cam/$code' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/login' | '/api/rtc' | '/call/$roomId' | '/cam/$code' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/rtc'
    | '/call/$roomId'
    | '/cam/$code'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiRtcRoute: typeof ApiRtcRoute
  CallRoomIdRoute: typeof CallRoomIdRoute
  CamCodeRoute: typeof CamCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$roomId': {
      id: '/call/$roomId'
      path: '/call/$roomId'
      fullPath: '/call/$roomId'
      preLoaderRoute: typeof CallRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cam/$code': {
      id: '/cam/$code'
      path: '/cam/$code'
      fullPath: '/cam/$code'
      preLoaderRoute: typeof CamCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiRtcRoute: ApiRtcRoute,
  CallRoomIdRoute: CallRoomIdRoute,
  CamCodeRoute: CamCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
